export const LOAD_THEATER_LIST = 'LOAD_THEATER_LIST';
export const SET_THEATER_LIST = 'SET_THEATER_LIST';
export const GET_THEATER_LIST = 'GET_THEATER_LIST';
export const GET_THEATER_BY_CITY = 'GET_THEATER_BY_CITY';

export const LOAD_MOVIE_LIST = 'LOAD_MOVIE_LIST';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';

